# Working with pandas dataframe

In [5]:
import pandas as pd
a = { 'Name': ['Ram', 'Shyam', 'Hari', 'Sita', 'Gita', 'bibek'],
    'Age': [24, 27, 22, 32, 20, 22],
    'City': ['Kathmandu', 'Bhaktapur', 'Bajhang', 'Lalitpur', 'Biratnagar', 'ilam'],
    'Marks': [14, 77, 62, 32, 80, 92]
}

In [7]:
df = pd.DataFrame(a)

In [8]:
df.to_csv('my_dataframe.csv', index=False)
print('DataFrame saved to my_dataframe.csv')

DataFrame saved to my_dataframe.csv

In [9]:
df.tail()

    Name  Age        City  Marks
1  Shyam   27   Bhaktapur     77
2   Hari   22     Bajhang     62
3   Sita   32    Lalitpur     32
4   Gita   20  Biratnagar     80
5  bibek   22        ilam     92

In [10]:

print(df.shape)

(6, 4)

In [11]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   City    6 non-null      str
 3   Marks   6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

In [13]:
print(df.describe())

             Age      Marks
count   6.000000   6.000000
mean   24.500000  59.500000
std     4.370355  30.382561
min    20.000000  14.000000
25%    22.000000  39.500000
50%    23.000000  69.500000
75%    26.250000  79.250000
max    32.000000  92.000000

In [14]:
print(df['Name'])

0      Ram
1    Shyam
2     Hari
3     Sita
4     Gita
5    bibek
Name: Name, dtype: str

In [15]:
print(df[['Name', 'City']])

    Name        City
0    Ram   Kathmandu
1  Shyam   Bhaktapur
2   Hari     Bajhang
3   Sita    Lalitpur
4   Gita  Biratnagar
5  bibek        ilam

In [16]:
print(df.iloc[0])

Name           Ram
Age             24
City     Kathmandu
Marks           14
Name: 0, dtype: object

In [17]:
print(df.loc[0])

Name           Ram
Age             24
City     Kathmandu
Marks           14
Name: 0, dtype: object

In [18]:
print(df.loc[0, 'Marks'])

14

In [19]:
df[df['Marks'] > 80]

    Name  Age  City  Marks
5  bibek   22  ilam     92

In [20]:
df[(df['Age'] > 20) & (df['Marks'] > 75)]

    Name  Age       City  Marks
1  Shyam   27  Bhaktapur     77
5  bibek   22       ilam     92

In [22]:
df['Grade'] = ['A', 'B-', 'A-', 'B+', 'C', 'A']
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     14     A
1  Shyam   27   Bhaktapur     77    B-
2   Hari   22     Bajhang     62    A-
3   Sita   32    Lalitpur     32    B+
4   Gita   20  Biratnagar     80     C
5  bibek   22        ilam     92     A

In [23]:

df['Marks'] = df['Marks']+5
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     19     A
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5  bibek   22        ilam     97     A

In [24]:
df.loc[df['Name'] == 'Ram', 'Marks'] = 95
print(df)

    Name  Age        City  Marks Grade
0    Ram   24   Kathmandu     95     A
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5  bibek   22        ilam     97     A

In [25]:
print(df.drop('Age', axis=1))

    Name        City  Marks Grade
0    Ram   Kathmandu     95     A
1  Shyam   Bhaktapur     82    B-
2   Hari     Bajhang     67    A-
3   Sita    Lalitpur     37    B+
4   Gita  Biratnagar     85     C
5  bibek        ilam     97     A

In [26]:
print(df.drop(0, axis=0))

    Name  Age        City  Marks Grade
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+
4   Gita   20  Biratnagar     85     C
5  bibek   22        ilam     97     A

In [27]:
sorted_desc_df = df.sort_values('Marks', ascending = False)
print(sorted_desc_df)

    Name  Age        City  Marks Grade
5  bibek   22        ilam     97     A
0    Ram   24   Kathmandu     95     A
4   Gita   20  Biratnagar     85     C
1  Shyam   27   Bhaktapur     82    B-
2   Hari   22     Bajhang     67    A-
3   Sita   32    Lalitpur     37    B+

In [28]:

data1 = {
    'Name': ['Ram', 'Shyam', 'Hari'],
    'Age': [24, 27, 22],
    'City': ['Kathmandu', 'Bhaktapur', 'Lalitpur']
}
data2 = {
    'Name': ['Sita', 'Gita', 'Rita'],
    'Age': [21, 21, 22],
    'City': ['Bajhang', 'Bajura', 'Doti']
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print('<-----------df1----------->')
print(df1)
print('<-----------df2----------->')
print(df2)

concatenated_df = pd.concat([df1, df2])
print('<------------concatenated df---------->')
print(concatenated_df)

<-----------df1----------->
    Name  Age       City
0    Ram   24  Kathmandu
1  Shyam   27  Bhaktapur
2   Hari   22   Lalitpur
<-----------df2----------->
   Name  Age     City
0  Sita   21  Bajhang
1  Gita   21   Bajura
2  Rita   22     Doti
<------------concatenated df---------->
    Name  Age       City
0    Ram   24  Kathmandu
1  Shyam   27  Bhaktapur
2   Hari   22   Lalitpur
0   Sita   21    Bajhang
1   Gita   21     Bajura
2   Rita   22       Doti

In [29]:
pd.read_csv('my_dataframe.csv')

    Name  Age        City  Marks
0    Ram   24   Kathmandu     14
1  Shyam   27   Bhaktapur     77
2   Hari   22     Bajhang     62
3   Sita   32    Lalitpur     32
4   Gita   20  Biratnagar     80
5  bibek   22        ilam     92

In [30]:
df.to_csv('file.csv')
pd.read_csv('file.csv')

   Unnamed: 0   Name  Age        City  Marks Grade
0           0    Ram   24   Kathmandu     95     A
1           1  Shyam   27   Bhaktapur     82    B-
2           2   Hari   22     Bajhang     67    A-
3           3   Sita   32    Lalitpur     37    B+
4           4   Gita   20  Biratnagar     85     C
5           5  bibek   22        ilam     97     A

In [35]:
import openpyxl
# 1. Create the student data
student_data = {
    'Name': ['Ram', 'Shyam', 'Sita', 'Gita'],
    'Age': [21, 22, 20, 21],
    'Marks': [85, 92, 78, 95],
    'Grade': ['A', 'A+', 'B', 'A+']
}

# 2. Convert to a DataFrame
df = pd.DataFrame(student_data)

# 3. Export to an Excel (.xlsx) file
# Note: index=False prevents Pandas from adding a row-number column
df.to_excel('students_report.xlsx', index=False)

print("Excel file '.xlsx' created successfully!")

Excel file '.xlsx' created successfully!